version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.4

jobs:
  build:
    docker:
      - image: 'circleci/python:latest-node'
    steps:
      - checkout
      - run: yarn install && yarn run deploy
      - aws-s3/sync:
          from: bucket
          to: 's3://smartcasa.org/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=3600"
          overwrite: true
