version: 2

jobs:
  build:
    working_directory: ~/dist
    docker:
      - image: 'circleci/node'
    steps:
      - attach_workspace:
          at: ~/dist
      - checkout
      - run: yarn install && yarn run deploy
      - persist_to_workspace:
          root: .
          paths: dist
  deploy-dev:
    working_directory: ~/dist
    docker:
      - image: 'circleci/python'
    steps:
      - attach_workspace:
          at: ~/dist
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: sync
          command: aws s3 sync dist s3://dev.smartcasa.org --acl public-read
      - run:
          name: set cache-control
          command: aws s3 cp s3://dev.smartcasa.org/ s3://dev.smartcasa.org/ --recursive --include "*" --exclude "*.json" --exclude "*.html" --metadata '{"cache-control":"max-age=31536000"}'
      - run:
          name: set cache-control for search index
          command: aws s3 cp s3://dev.smartcasa.org/lunr-index.json s3://dev.smartcasa.org/lunr-index.json --metadata '{"cache-control":"max-age=3600"}'
      - run:
          name: set cache-control for index
          command: aws s3 cp s3://dev.smartcasa.org/index.html s3://dev.smartcasa.org/index.html --metadata '{"cache-control":"public, must-revalidate, proxy-revalidate, max-age=0"}'
  deploy-prod:
    working_directory: ~/dist
    docker:
      - image: 'circleci/python'
    steps:
      - attach_workspace:
          at: ~/dist
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: sync
          command: aws s3 sync dist s3://smartcasa.org --acl public-read
      - run:
          name: set cache-control
          command: aws s3 cp s3://smartcasa.org/ s3://smartcasa.org/ --recursive --include "*" --exclude "*.json" --exclude "*.html" --metadata '{"cache-control":"max-age=31536000"}'
      - run:
          name: set cache-control for search index
          command: aws s3 cp s3://smartcasa.org/lunr-index.json s3://smartcasa.org/lunr-index.json --metadata '{"cache-control":"max-age=3600"}'
      - run:
          name: set cache-control for index
          command: aws s3 cp s3://smartcasa.org/index.html s3://smartcasa.org/index.html --metadata '{"cache-control":"public, must-revalidate, proxy-revalidate, max-age=0"}'

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy-dev:
          filters:
            branches:
              only: master
          requires:
            - build
      - manual-check:
          type: approval
          requires:
            - deploy-dev
      - deploy-prod:
          filters:
            branches:
              only: master
          requires:
            - manual-check
